name: Deploy Web App with SQL using Bicep

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: "yousma-web"
  AZURE_RESOURCE_GROUP: "yousma-rg"
  BICEP_FILE_PATH: "./infra/main.bicep"
  CONNECTION_STRING_NAME: "SQLCONNSTR_DB_CONNECTION"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group create \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --template-file ${{ env.BICEP_FILE_PATH }} \
              --parameters webAppName=${{ env.AZURE_WEBAPP_NAME }}

      - name: Deploy Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
