name: Deploy Web App with SQL using Bicep

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: yousma=web
  AZURE_RESOURCE_GROUP: yousma-rg
  BICEP_FILE_PATH: ./infra/main.bicep
  CONNECTION_STRING_NAME: SQLCONNSTR_DB_CONNECTION

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep using ARM Deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ${{ env.BICEP_FILE_PATH }}
          parameters: >
            sqlServerName=${{ secrets.SQL_SERVER_NAME }}
            sqlAdmin=${{ secrets.SQL_ADMIN }}
            sqlPassword=${{ secrets.SQL_PASSWORD }}
            databaseName=${{ secrets.SQL_DB_NAME }}
            webAppName=${{ env.AZURE_WEBAPP_NAME }}

      - name: Set Web App Connection String from Secret
        run: |
          az webapp config connection-string set \
            --resource-group $AZURE_RESOURCE_GROUP \
            --name $AZURE_WEBAPP_NAME \
            --settings $CONNECTION_STRING_NAME="${{ secrets.DB_CONNECTION_STRING }}" \
            --connection-string-type SQLAzure
